twitter:
    -
        url: 'https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=kchristofilos&count=5'
        owner: K.Christofilos
        object: Tweet
        map:
            - { source: object, relation: BELONGS_TO, destination: owner }
    -
        url: 'https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=kchristofilos&count=5'
        owner: K.Christofilos
        object: Tweet
        map: {  }
